### ISSUE TITLE
Installing on linux - somafm not found

### ISSUE THREAD

**Issue by arozans** [rockymadden/somafm-cli#11]
Hello,
thanks for sharing this code.

When I follow the installation instructions there is no console output and `somafm` is not recognized as a command. I have installed all dependecies with apt-get before `make`.
Did I miss something?

**Comment by rockymadden** [comment]
You bet! @arozans Can you confirm that the script is in a directory on your `PATH`? I just checked the docs and it doesn't explicitly state this little tidbit. You can confirm it works `./somafm` instead of `somafm`. The latter would require it being in your `PATH`.

**Comment by arozans** [comment]
Oh yes. You're right. I should have thought about that. I will move `somafm` to my ~/bin directory. Thx.
