### ISSUE TITLE
[REJECTED] Windows standalone binary

### ISSUE THREAD

**Issue by sergeevabc** [rockymadden/somafm-cli#4]
Dear Rocky,
Could you be so kind to generate ```.exe``` for the rest of us who use Windows only, if possible?

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by rockymadden** [comment]
I believe it should be possible to use via Bash on Ubuntu on Windows. As far as an `.exe`, I don't have any personal desire/ability to go that route but would welcome PRs, perhaps, to do so.
